#!/bin/bash

options=(
    hidpi=on
    width=20.0
    active_color=0xff0096FF
    # inactive_color=0xffFF0000
    inactive_color=0xff00FFFF
    # active_color="gradient(top_left=0xffFF0000,bottom_right=0xff00FF00)"
)

borders "${options[@]}"#
